import { CommandNode } from "./CommandNode.js";

export const COMMAND_TREE: CommandNode[] = [
  {
    name: "人事",
    description: "人材の登用・探索・育成を行う",
    children: [
      { name: "在野登用", description: "どこにも所属していない、居場所の分かっている人物を登用する。臣下・お金・アーティファクト・期間を指定する" },
      { name: "人材探索", description: "臣下・お金・期間を指定して人材を探させる。範囲は全域・指定拠点周辺・勢力内から選ぶ" },
      { name: "引き抜き", description: "他勢力に仕えている人物を自勢力に引き込む。相手によっては殺し合いや戦争になる" },
      { name: "修行の旅", description: "資金と期間を指定して人物を研鑽の旅に出す。成果が出ないこともある" },
    ],
  },
  {
    name: "軍事",
    description: "進軍・訓練・討伐など軍に関わる指示を出す",
    children: [
      { name: "進軍", description: "進軍元と進軍先を指定する。ターンが進行してから進軍を開始する" },
      { name: "ダンジョン攻略", description: "遠征元の拠点とダンジョンを指定して攻略させる。派遣元の拠点は防衛が手薄になる" },
      { name: "戦闘訓練", description: "拠点にいる兵士と人物の訓練度を上げる" },
      { name: "防衛訓練", description: "戦争やハクスラなど戦闘全般での防御力を鍛える" },
      { name: "賊狩り", description: "民の生活を脅かす賊の根城を討伐する。成功すると資金が手に入り、まれにアーティファクトや人材も得る" },
    ],
  },
  {
    name: "商人",
    description: "商人を通じて武具やアーティファクトを売買する",
    children: [
      { name: "鍛冶依頼", description: "商人を通じて鍛冶師に設計図の武具を依頼する。投資額と納期で出来が変わる" },
      { name: "兵士装備選定", description: "兵士が装備する武具を選ぶ。強い武具ほど高価で、兵士を雇う単価も上がる" },
      { name: "アーティファクト購入", description: "誰かが売りに出したアーティファクトを買う" },
      { name: "アーティファクト売却", description: "手持ちのアーティファクトを売る" },
      { name: "専属契約", description: "商人個人と契約して御用商人にする。商人が違法品で摘発されると信望が大きく落ちる" },
    ],
  },
  {
    name: "内政",
    description: "災害への備えや民心・汚職への対応を行う",
    children: [
      { name: "災害対策", description: "発生した襲撃・疫病・洪水などの災害に対応する" },
      { name: "予防策", description: "あらゆる災害に事前に備える" },
      { name: "民心掌握", description: "投資額を決めて炊き出しや歩道整備などを行い、民意をつかむ" },
      { name: "汚職調査", description: "汚職している者を洗い出す。失敗すると臣下と民の心が離れる" },
      { name: "汚職断罪", description: "汚職した者を断罪する。真面目な臣下の信望を得るが、汚職している臣下は裏切りやすくなる" },
    ],
  },
  {
    name: "調略",
    description: "他勢力への工作や暗殺など裏の手を打つ",
    children: [
      { name: "身辺調査", description: "人物の信望・汚職の有無・裏切りの予定など、表に出ない情報を調べる。発覚すると臣下の大半が不信を抱く" },
      { name: "駆虎呑狼", description: "指定した国に、指定した場所を攻めるよう誘導する" },
      { name: "内応調略", description: "他勢力の人物を、本人が自発的に寝返ったように見せて引き込む" },
      { name: "攪乱工作", description: "指定場所の治安悪化や都市機能の麻痺を起こす。やりすぎると全勢力から敵視される" },
      { name: "離間計", description: "偽情報で他勢力同士の関係を悪化させる、または対象勢力の信望を貶める" },
      { name: "暗殺", description: "実行者の信望と能力で結果が変わる。失敗すると周囲に知られやすい" },
      {
        name: "三十六計",
        description: "兵法書「三十六計」に由来する計略を選ぶ",
        children: [
          { name: "囲魏救趙", description: "本命を直接攻めず、その本拠地や弱点を突いて間接的に退かせる" },
          { name: "借刀殺人", description: "他者の手を借りて対象を排除する" },
          { name: "趁火打劫", description: "相手が災害や内乱で混乱している隙に乗じる" },
          { name: "声東撃西", description: "別の場所を攻めると見せかけ、本命を奇襲する" },
          { name: "隔岸観火", description: "敵対する勢力同士を放置し、疲弊するのを傍観する" },
          { name: "打草驚蛇", description: "小さく揺さぶり、相手の反応から隠れた動きを探る" },
          { name: "調虎離山", description: "有利な地の敵を誘い出し、不利な場所で叩く" },
          { name: "抛磚引玉", description: "小さな餌で相手を誘い出し、大きな成果を得る" },
          { name: "擒賊擒王", description: "まず首魁を狙い、組織ごと崩す" },
          { name: "釜底抽薪", description: "資金や補給など相手の戦力の根本を断つ" },
          { name: "金蝉脱殻", description: "自軍の存在を偽装したまま、主力をひそかに動かす" },
          { name: "関門捉賊", description: "逃げ場を塞いでから敵を追い詰める" },
          { name: "遠交近攻", description: "遠方の勢力と友好を結び、近隣の勢力を攻める" },
          { name: "美人計", description: "魅力的な人物を送り込み、相手の判断力や忠誠心を揺さぶる" },
          { name: "反間計", description: "敵の間者を寝返らせ、二重スパイとして使う" },
          { name: "走為上", description: "勝ち目がないとき、被害を抑えて撤退する" },
        ],
      },
    ],
  },
  {
    name: "外交",
    description: "他勢力との条約や交渉を行う",
    children: [
      { name: "親善交渉", description: "金かアーティファクトを送り合い、友好を示す" },
      { name: "不可侵条約", description: "1年単位で相互不可侵を結ぶ。2年以上はほとんど成立しない" },
      { name: "自由通商同盟", description: "交易を自由化する。相手が鍛冶依頼で作った武具を仕入れやすくなる" },
      { name: "同盟結束", description: "親善・不可侵・自由通商をまとめた同盟。毎ターン維持費がかかる" },
      { name: "降伏勧告", description: "相手に降伏を迫る。いきなり強国へ送ると使者が処刑される" },
      { name: "笑裏藏刀", description: "友好を装いながら、裏で相手の評判を貶める情報を流す" },
    ],
  },
  {
    name: "情報",
    description: "自国と世界の状況を確認する",
    children: [
      { name: "歴史", description: "自国で起きた出来事を年表形式で確認する" },
      { name: "世界情勢", description: "調査済みの範囲で、拠点や勢力の情報を確認する" },
      { name: "人材調査状況", description: "人物ごとに判明している情報を確認する" },
      { name: "信望", description: "世界からプレイヤーへ向けられている信望を確認する" },
      { name: "評価", description: "プレイヤーから各人材への評価を確認する" },
    ],
  },
  {
    name: "設定",
    description: "画面・サウンド・セーブなどの設定を行う",
    children: [
      { name: "画面設定", description: "画面サイズ・フォント・ウィンドウ/フルスクリーンを設定する" },
      { name: "サウンド設定", description: "BGM・SEの音量やBGMファイルを設定する" },
      { name: "セーブ", description: "現在の状態を保存する" },
      { name: "ロード", description: "保存した状態を読み込む" },
      { name: "終了", description: "ゲームを終了する" },
    ],
  },
];
